apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: petclinic
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: petclinic
spec:
  ports:
    - port: 3306
  selector:
    app: petclinic
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mysql
  labels: 
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysqldb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_USER
          value: "petclinic"
        - name: MYSQL_PASSWORD
          value: "petclinic"
        - name: MYSQL_DATABASE
          value: "petclinic"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
